/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SEPackageSM;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rajendra
 */
class Customer 
{
        private String Name;
	private String Address;
	private String Telephone;
	private String DL_no;
	private int    Customer_ID;
	private float   Total_Purchase;

	public Customer(String Name_in,String Address_in, String Telephone_in, String DL_no_in, int Customer_ID_in,float purchase)
	{
                Name=Name_in;
		Address     = Address_in;
		Telephone   = Telephone_in;
		DL_no       = DL_no_in;			
		Customer_ID = Customer_ID_in;
                Total_Purchase=purchase;
	}

	public String Address ()        { return Address;   }
	public String Telephone ()      { return Telephone ;}
	public String DL_no ()          { return DL_no;     }
	public int    Customer_ID ()    { return Customer_ID;}
	public float  Total_Purchase () { return Total_Purchase; }
        public String Name()            { return Name;}

	public void Add_Purchase ( float addPurchase ) {  Total_Purchase = Total_Purchase + addPurchase ; }

	public boolean Greater_T_10K() { if (Total_Purchase > 10000) return true; 
		else return false; }
	}
public class StartGUI extends javax.swing.JFrame {

    /**
     * Creates new form StartGUI
     */
    private ArrayList <Customer> profile=new ArrayList();
    private ArrayList <Customer> oldprofile=new ArrayList();
    private int cn=0;
    public StartGUI() throws IOException {
        initComponents();
        oldpro();
        PurchasePanel.setVisible(false);
        RegisterPanel.setVisible(false);
        Above10kPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        PurchasePanel = new javax.swing.JPanel();
        EnterP = new javax.swing.JButton();
        AmountField = new javax.swing.JTextField();
        CustomerField = new javax.swing.JTextField();
        BackPurchase = new javax.swing.JButton();
        BgPurchaserPage = new javax.swing.JLabel();
        RegisterPanel = new javax.swing.JPanel();
        Enter = new javax.swing.JButton();
        BackRegister = new javax.swing.JButton();
        DrivingField = new javax.swing.JTextField();
        TelField = new javax.swing.JTextField();
        AddressPane = new javax.swing.JScrollPane();
        AddressArea = new javax.swing.JTextArea();
        NameField = new javax.swing.JTextField();
        BgRegisterPage = new javax.swing.JLabel();
        StartPanel = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        GoldLabel = new javax.swing.JLabel();
        SurpriseGift = new javax.swing.JLabel();
        Above10kSalesLabel = new javax.swing.JLabel();
        PurchaseLabel = new javax.swing.JLabel();
        RegisterLabel = new javax.swing.JLabel();
        BgStartPage = new javax.swing.JLabel();
        Above10kPanel = new javax.swing.JPanel();
        Above10kPane = new javax.swing.JScrollPane();
        Above10kArea = new javax.swing.JTextArea();
        Exit1 = new javax.swing.JButton();
        Above10kLabel = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(202, 253));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PurchasePanel.setMinimumSize(new java.awt.Dimension(202, 253));
        PurchasePanel.setPreferredSize(new java.awt.Dimension(202, 253));
        PurchasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EnterP.setBackground(new java.awt.Color(51, 102, 255));
        EnterP.setForeground(new java.awt.Color(102, 0, 0));
        EnterP.setText("ENTER");
        EnterP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EnterP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EnterP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterPMouseClicked(evt);
            }
        });
        EnterP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterPActionPerformed(evt);
            }
        });
        PurchasePanel.add(EnterP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        AmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountFieldActionPerformed(evt);
            }
        });
        PurchasePanel.add(AmountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 204, 150, 30));

        CustomerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerFieldActionPerformed(evt);
            }
        });
        PurchasePanel.add(CustomerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 30));

        BackPurchase.setBackground(new java.awt.Color(51, 102, 255));
        BackPurchase.setForeground(new java.awt.Color(102, 0, 0));
        BackPurchase.setText("BACK");
        BackPurchase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackPurchase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackPurchaseMouseClicked(evt);
            }
        });
        BackPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackPurchaseActionPerformed(evt);
            }
        });
        PurchasePanel.add(BackPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        BgPurchaserPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackageSM/Image/PurchaseForm.png"))); // NOI18N
        PurchasePanel.add(BgPurchaserPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PurchasePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        RegisterPanel.setMinimumSize(new java.awt.Dimension(202, 253));
        RegisterPanel.setPreferredSize(new java.awt.Dimension(202, 253));
        RegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Enter.setBackground(new java.awt.Color(51, 102, 255));
        Enter.setForeground(new java.awt.Color(102, 0, 0));
        Enter.setText("ENTER");
        Enter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterMouseClicked(evt);
            }
        });
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });
        RegisterPanel.add(Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        BackRegister.setBackground(new java.awt.Color(51, 102, 255));
        BackRegister.setForeground(new java.awt.Color(102, 0, 0));
        BackRegister.setText("BACK");
        BackRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackRegisterMouseClicked(evt);
            }
        });
        BackRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackRegisterActionPerformed(evt);
            }
        });
        RegisterPanel.add(BackRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        DrivingField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrivingFieldActionPerformed(evt);
            }
        });
        RegisterPanel.add(DrivingField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, 22));

        TelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelFieldActionPerformed(evt);
            }
        });
        RegisterPanel.add(TelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 160, 80, -1));

        AddressArea.setColumns(20);
        AddressArea.setLineWrap(true);
        AddressArea.setRows(5);
        AddressPane.setViewportView(AddressArea);

        RegisterPanel.add(AddressPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 50));
        RegisterPanel.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 66, 90, -1));

        BgRegisterPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackageSM/Image/RegisterForm.png"))); // NOI18N
        RegisterPanel.add(BgRegisterPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(RegisterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        StartPanel.setMinimumSize(new java.awt.Dimension(202, 253));
        StartPanel.setPreferredSize(new java.awt.Dimension(202, 253));
        StartPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartPanelMouseClicked(evt);
            }
        });
        StartPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setForeground(new java.awt.Color(51, 0, 0));
        Exit.setText("EXIT");
        Exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 51, 0)));
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        StartPanel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 50, -1));

        GoldLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 1, true));
        GoldLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GoldLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoldLabelMouseClicked(evt);
            }
        });
        StartPanel.add(GoldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 20));

        SurpriseGift.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 1, true));
        SurpriseGift.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SurpriseGift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SurpriseGiftMouseClicked(evt);
            }
        });
        StartPanel.add(SurpriseGift, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        Above10kSalesLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 1, true));
        Above10kSalesLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Above10kSalesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Above10kSalesLabelMouseClicked(evt);
            }
        });
        StartPanel.add(Above10kSalesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 40));

        PurchaseLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 1, true));
        PurchaseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PurchaseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PurchaseLabelMouseClicked(evt);
            }
        });
        StartPanel.add(PurchaseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 63, 90, 20));

        RegisterLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 1, true));
        RegisterLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterLabelMouseClicked(evt);
            }
        });
        StartPanel.add(RegisterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 20));

        BgStartPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackageSM/Image/StartPage.png"))); // NOI18N
        StartPanel.add(BgStartPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(StartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 202, 253));

        Above10kPanel.setMinimumSize(new java.awt.Dimension(202, 253));
        Above10kPanel.setPreferredSize(new java.awt.Dimension(202, 253));
        Above10kPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Above10kPane.setOpaque(false);

        Above10kArea.setEditable(false);
        Above10kArea.setBackground(new java.awt.Color(0, 0, 0));
        Above10kArea.setColumns(20);
        Above10kArea.setForeground(new java.awt.Color(255, 255, 255));
        Above10kArea.setLineWrap(true);
        Above10kArea.setRows(5);
        Above10kPane.setViewportView(Above10kArea);

        Above10kPanel.add(Above10kPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 150));

        Exit1.setForeground(new java.awt.Color(51, 0, 0));
        Exit1.setText("BACK");
        Exit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(153, 102, 0), new java.awt.Color(153, 51, 0)));
        Exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit1MouseClicked(evt);
            }
        });
        Above10kPanel.add(Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 50, -1));

        Above10kLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackageSM/Image/Above10k.png"))); // NOI18N
        Above10kPanel.add(Above10kLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(Above10kPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 202, 253));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelFieldActionPerformed

    private void DrivingFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrivingFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrivingFieldActionPerformed

    private void CustomerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerFieldActionPerformed

    private void AmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountFieldActionPerformed

    private void RegisterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLabelMouseClicked
       StartPanel.setVisible(false);
       RegisterPanel.setVisible(true);
    }//GEN-LAST:event_RegisterLabelMouseClicked

    private void PurchaseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchaseLabelMouseClicked
        StartPanel.setVisible(false);
       PurchasePanel.setVisible(true);
    }//GEN-LAST:event_PurchaseLabelMouseClicked

    private void BackRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackRegisterActionPerformed
    private void setCN(int cn)
    {
        try {
            PrintWriter pw=new PrintWriter("C:\\Users\\Rajendra\\Documents\\NetBeansProjects\\SuperMarket\\CN.txt");
            pw.print(""+cn);
            pw.close();
        } catch (IOException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void BackRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackRegisterMouseClicked
       setCN(cn);
       StartPanel.setVisible(true);
       RegisterPanel.setVisible(false);
    }//GEN-LAST:event_BackRegisterMouseClicked

    private void BackPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackPurchaseMouseClicked
        StartPanel.setVisible(true);
       PurchasePanel.setVisible(false);
    }//GEN-LAST:event_BackPurchaseMouseClicked

    private void BackPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackPurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackPurchaseActionPerformed
    private int getCN() throws IOException
    {
        FileReader fr=null;
        int cn;
        String s="";
        try {
            fr=new FileReader("C:\\Users\\Rajendra\\Documents\\NetBeansProjects\\SuperMarket\\CN.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            s=new BufferedReader(fr).readLine();
        } catch (IOException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        cn=Integer.parseInt(s);
        fr.close();
        return cn;
    }
    private void EnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterMouseClicked
        if(NameField.getText().equals("") || TelField.getText().equals("") || DrivingField.getText().equals("") || AddressArea.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please fill up the Form.");
        else{
        int tel,flag=0;
        try {
        cn=getCN();
        }
        catch(Exception e)
        {
        }
        try {
            tel=Integer.parseInt(TelField.getText());
            } catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"Please enter valid Phone Number");
                flag=1;   
            }
        if(flag==0){
        profile.add(new Customer(NameField.getText(),AddressArea.getText(),TelField.getText(),DrivingField.getText(),cn,0));
        JOptionPane.showMessageDialog(null,"Please note down your CustomerID:\n"+cn++);
        setCN(cn);
            NameField.setText("");
            TelField.setText("");
            DrivingField.setText("");
            AddressArea.setText("");
        }
        else
            TelField.setText("");
        }
    }//GEN-LAST:event_EnterMouseClicked

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterActionPerformed

    private void EnterPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterPMouseClicked
        if(AmountField.getText().equals("") || CustomerField.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please fill up the Form.");
        else{            
        int CN=Integer.parseInt(CustomerField.getText()),flag=0;
        float pur;
        try {
            cn=getCN();
        } catch (IOException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pur=Float.parseFloat(AmountField.getText());
            } catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null,"Please enter valid Amount.");
                flag=1;
            }
        if(flag==0)
        if(CN>=cn)
            JOptionPane.showMessageDialog(null, "Invalid CN Number. Please re-enter.");
        else
        {
            if(CN>oldprofile.size())
            {
                profile.get(cn-CN-1).Add_Purchase(Float.parseFloat(AmountField.getText()));
            }
            else
            {
                oldprofile.get(CN-1).Add_Purchase(Float.parseFloat(AmountField.getText()));
            }
        }
        if(flag==1)
            AmountField.setText("");
        else
        {
            AmountField.setText("");
            CustomerField.setText("");
        }
        }
    }//GEN-LAST:event_EnterPMouseClicked

    private void EnterPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterPActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        int i;
        String s;
        BufferedWriter bw=null;
        try {
            bw=new BufferedWriter(new FileWriter("C:\\Users\\Rajendra\\Documents\\NetBeansProjects\\SuperMarket\\CustomerData.txt",false));
        } catch (IOException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        Customer cl;
        Object c[]=oldprofile.toArray();
        for(i=0;i<oldprofile.size();i++)
        {
            
            cl=(Customer)c[i];
            s=cl.Customer_ID()+"*"+cl.Total_Purchase()+"*"+cl.Name()+"*"+cl.Address()+"*"+cl.Telephone()+"*"+cl.DL_no()+"*";
            try {
                bw.write(s);
                bw.newLine();
            } catch (IOException ex) {
                Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Object c2[]=profile.toArray();
        for(i=0;i<profile.size();i++)
        {
            
            cl=(Customer)c2[i];
            s=cl.Customer_ID()+"*"+cl.Total_Purchase()+"*"+cl.Name()+"*"+cl.Address()+"*"+cl.Telephone()+"*"+cl.DL_no()+"*";
            try {
                bw.write(s);
                bw.newLine();
            } catch (IOException ex) {
                Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void GoldLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoldLabelMouseClicked
        String s="";
        int cnt=1;
        StartPanel.setVisible(false);
        Above10kPanel.setVisible(true);
        int i;
        for(i=0;i<profile.size();i++)
        {
            if(profile.get(i).Greater_T_10K()==true)
                s+=(cnt++)+". Name :"+profile.get(i).Name()+"\n"+"Address :"+profile.get(i).Address()+"\n\n";
            
        }
        for(i=0;i<oldprofile.size();i++)
        {
            if(oldprofile.get(i).Greater_T_10K()==true)
                s+=(cnt++)+". Name :"+oldprofile.get(i).Name()+"\n"+"Address :"+oldprofile.get(i).Address()+"\n\n";
        }
        Above10kArea.setText(s);
    }//GEN-LAST:event_GoldLabelMouseClicked

    private void Above10kSalesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Above10kSalesLabelMouseClicked
        String s="";
        int cnt=1;
        StartPanel.setVisible(false);
        Above10kPanel.setVisible(true);
        int i;
        for(i=0;i<profile.size();i++)
        {
            if(profile.get(i).Greater_T_10K()==true)
                s+=(cnt++)+". Name :"+profile.get(i).Name()+"\n"+"Address :"+profile.get(i).Address()+"\n\n";
            
        }
        for(i=0;i<oldprofile.size();i++)
        {
            if(oldprofile.get(i).Greater_T_10K()==true)
                s+=(cnt++)+". Name :"+oldprofile.get(i).Name()+"\n"+"Address :"+oldprofile.get(i).Address()+"\n\n";
        }
        Above10kArea.setText(s);
    }//GEN-LAST:event_Above10kSalesLabelMouseClicked

    private void StartPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartPanelMouseClicked
        
    }//GEN-LAST:event_StartPanelMouseClicked

    private void Exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit1MouseClicked
        StartPanel.setVisible(true);
        Above10kPanel.setVisible(false);
    }//GEN-LAST:event_Exit1MouseClicked

    private void SurpriseGiftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SurpriseGiftMouseClicked
        StartPanel.setVisible(false);
        Above10kPanel.setVisible(true);
        int i;
        String s="";
        float pur=0;
        //s="Name :"+profile.get(0).Name()+"\n"+"Address :"+profile.get(0).Address()+"\n\n";
        for(i=0;i<profile.size();i++)
        {
            if(profile.get(i).Total_Purchase()>=pur)
            {
                if(profile.get(i).Total_Purchase()==pur)
                {
                    s+="Name :"+profile.get(i).Name()+"\n"+"Address :"+profile.get(i).Address()+"\n\n";
                }
                else
                {
                    s="Name :"+profile.get(i).Name()+"\n"+"Address :"+profile.get(i).Address()+"\n\n";
                }
                pur=profile.get(i).Total_Purchase();
            }
        }
        for(i=0;i<oldprofile.size();i++)
        {
            if(oldprofile.get(i).Total_Purchase()>=pur)
            {
                if(oldprofile.get(i).Total_Purchase()==pur)
                {
                    s+="Name :"+oldprofile.get(i).Name()+"\n"+"Address :"+oldprofile.get(i).Address()+"\n\n";
                }
                else
                {
                    s="Name :"+oldprofile.get(i).Name()+"\n"+"Address :"+oldprofile.get(i).Address()+"\n\n";
                }
                pur=oldprofile.get(i).Total_Purchase();
            }
        }
        StartPanel.setVisible(false);
        Above10kPanel.setVisible(true);
        Above10kArea.setText("Congratulations!!!!!!\n\n"+s);
    }//GEN-LAST:event_SurpriseGiftMouseClicked

    /**
     * @param args the command line arguments
     */
    public void oldpro() throws IOException
    {
        FileReader fr=null;
        String s="";
        try {
            fr=new FileReader("C:\\Users\\Rajendra\\Documents\\NetBeansProjects\\SuperMarket\\CustomerData.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedReader br=new BufferedReader(fr);
        while((s=br.readLine())!=null)
        {
            String ends = "*";
            StringTokenizer scanner;   
            scanner = new StringTokenizer(s, ends, false);
            ArrayList al = new ArrayList();
            while (scanner.hasMoreTokens()) 
            {
                String aWord = scanner.nextToken();
                al.add(aWord);
            }
            Object arr[] = al.toArray();
            Customer cust = new Customer((String)arr[2], (String)arr[3], (String)arr[4],(String)arr[5], Integer.parseInt((String)arr[0]),Float.parseFloat((String) arr[1]));
            oldprofile.add(cust);
        }
    }
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StartGUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Above10kArea;
    private javax.swing.JLabel Above10kLabel;
    private javax.swing.JScrollPane Above10kPane;
    private javax.swing.JPanel Above10kPanel;
    private javax.swing.JLabel Above10kSalesLabel;
    private javax.swing.JTextArea AddressArea;
    private javax.swing.JScrollPane AddressPane;
    private javax.swing.JTextField AmountField;
    private javax.swing.JButton BackPurchase;
    private javax.swing.JButton BackRegister;
    private javax.swing.JLabel BgPurchaserPage;
    private javax.swing.JLabel BgRegisterPage;
    private javax.swing.JLabel BgStartPage;
    private javax.swing.JTextField CustomerField;
    private javax.swing.JTextField DrivingField;
    private javax.swing.JButton Enter;
    private javax.swing.JButton EnterP;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Exit1;
    private javax.swing.JLabel GoldLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel PurchaseLabel;
    private javax.swing.JPanel PurchasePanel;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JLabel SurpriseGift;
    private javax.swing.JTextField TelField;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
